In [ ]:
#1. Viết chương trình nhập vào 2 giá trị a, b và tính tổng, hiệu, tích thương của a và b
#Input
a = int(input("Nhập a: "))
b = int(input("Nhập b: "))
#Tổng
output = a + b
print(output)
#Hiệu
output = a - b
print(output)
#Tích
output = a * b
print(output)
#Thương
output = a / b
print(output)

Nhập a: 2
Nhập b: 3
5
-1
6
0.6666666666666666


In [ ]:
#2. Lấy các ký tự từ chỉ số 2 đến chỉ số 4 (llo) của chuỗi "Hello World"
string = "Hello World"
print(string[2:5])

llo


In [ ]:
#3. Xóa khoảng trắng thừa ở đầu và cuối chuỗi "Hello World". Chuyển chuỗi sang dạng hoa và thường. Thay ký tự H thành ký tự J
string = " Hello World "
print(string.strip())
print(string.upper())
print(string.lower())
temp = string.replace("H","J")
print(temp)

Hello World
 HELLO WORLD 
 hello world 
 Jello World 


In [96]:
#4. In ra "Hello World!" nếu a > b
#Input
a = int(input("Nhập a: "))
b = int(input("Nhập b: "))
#Điều kiện nếu a > b thì in ra "Hello World!"
if a > b:
  print("Hello World!")


Nhập a: 8
Nhập b: 4
Hello World!


In [97]:
#5. In ra "Yes" nếu a = b, ngược lại in "No"
#Input
a = int(input("Nhập a: "))
b = int(input("Nhập b: "))
#Điều kiện In ra "Yes" nếu a = b, ngược lại in "No"
if a == b:
  print("Yes")
else:
  print("No")

Nhập a: 6
Nhập b: 6
Yes


In [94]:
#6. In 1 nếu a = b, in 2 nếu a > b, in 3 nếu ngược lại
#Input
a = int(input("Nhập a: "))
b = int(input("Nhập b: "))
#Điều kiện In 1 nếu a = b, in 2 nếu a > b, in 3 nếu ngược lại
if a == b:
  print(1)
elif a > b:
  print(2)
else:
  print(3)

Nhập a: 2
Nhập b: 7
3


In [92]:
#7. In ra "Hello World!" nếu a = b và b = d
#Input
a = int(input("Nhập a: "))
b = int(input("Nhập b: "))
d = int(input("Nhập d: "))
#Điều kiện In ra "Hello World!" nếu a = b và b = d
if a == b and b == d:
  print("Hello World!")

Nhập a: 3
Nhập b: 3
Nhập d: 3
Hello World!


In [91]:
#8. In ra "Hello World!" nếu a = b hoặc c = d
#Input
a = int(input("Nhập a: "))
b = int(input("Nhập b: "))
c = int(input("Nhập c: "))
d = int(input("Nhập d: "))
#Điều kiện In ra "Hello World!" nếu a = b hoặc c = d
if a == b or c == d:
  print("Hello World!")

Nhập a: 3
Nhập b: 3
Nhập c: 7
Nhập d: 4
Hello World!


In [90]:
#9. Viết lại câu lệnh if... else sau lên cùng 1 dòng
#Input
a = int(input("Nhập a: "))
b = int(input("Nhập b: "))
#Điều kiện và output
print("Yes") if a > b else print("No")

Nhập a: 3
Nhập b: 4
No


In [89]:
#10. Nhập vào 2 số a, b. Thực hiện câu lệnh và cho biết kết quả print("A") if a>b else print("=") if a == b else print("B")
#Input
a = int(input("Nhập a: "))
b = int(input("Nhập b: "))
#Điều kiện
print("A") if a > b else print("=") if a == b else print("B")

Nhập a: 4
Nhập b: 7
B


In [12]:
#11. Tạo mảng số nguyên a với n phần tử và mảng b chỉ chứa các phần tử chẵn của a
#Input n phần tử
n = int(input("Nhập số phần tử trong mảng: "))
#Vòng lặp for input giá trị phần tử vào mảng
a = []
b = []
for i in range(n):
  a.append(int(input("Nhập giá trị phần tử: ")))
for i in a:
  if i % 2 == 0:
    b.append(i) #Mảng b chỉ chứa các phần tử chẵn của a
print(a)
print(b)

Nhập số phần tử trong mảng: 3
Nhập giá trị phần tử: 2
Nhập giá trị phần tử: 3
Nhập giá trị phần tử: 1
[2, 3, 1]


In [ ]:
#12. Viết chương trình tính tổng các số từ 0 đến 999 mà là bội của 3 hoặc 5
sum = 0;
for i in range(1000):
  if i % 3 == 0 or i % 5 == 0:
    sum += i
print(sum)

In [33]:
#13. Viết hàm trộn 2 mảng một chiều thành 1 mảng một chiều với mỗi phần tử của mảng mới là tổng của 2 phần tương ứng từ 2 mảng cho trước.
#Trong quá trình trộn 2 mảng nếu mảng nào còn phần tử thì các phần tử còn lại của mảng đó sẽ đưa vào mảng mới
a = [2, 3, 6, 9, 10]
b = [3, 5, 7]
c = []
dodai = min(len(a), len(b))
for i in range(dodai):
  c.append(a[i] + b[i])
if len(a)>len(b):
  for i in range(dodai, len(a)):
    c.append(a[i])
else:
  for i in range(dodai, len(b)):
    c.append(b[i])
print(c)

[5, 8, 13, 9, 10]


In [70]:
#14. Cho mảng 2 chiều a có m dòng, n cột chứa số nguyên
#a) Tạo mảng a chứa các số nguyên ngẫu nhiên
import numpy as np
import random
m = int(input("Nhập dòng: ")) #Dòng
n = int(input("Nhập cột: ")) #Cột
a = [[random.randint(1,100) for i in range (n)] for i in range(m)]
a = np.array(a)
print(a)

#b) Xuất các phần tử thuộc dòng k
k = int(input("Dòng muốn xuất: ")) #Nhập dòng k vào
print(a[k])

#c) Xuất các phần tử thuộc cột k
k = int(input("Cột muốn xuất: "))
for i in range(len(a)):
  print(a[i][k])

#d) Tìm dòng có tổng lớn nhất (45??)
dongTongLonNhat = 0
max = np.sum(a[0])
for i in range(1, len(a)):
  tong = np.sum(a[i])
  if(tong>max):
    dongLonNhat = i
    max = tong
print(f"Dòng lớn nhất là: {dongTongLonNhat}")

#e) Tìm cột có tích nhỏ nhất
cotTichNhoNhat = -1
min = -1
for i in range(len(a[0])):
  tich = 1
  for j in range(len(a)):
    tich *= a[j][i]
  if(tich<min or min==-1):
    cotTichNhoNhat = i
print(f"Cột có tích nhỏ nhất là: {cotTichNhoNhat}")

#f) Xuất ra các phần tử thuộc dòng chẵn và cột lẻ trong a
print("Các phần tử thuộc dòng chẵn và cột lẻ trong a là: ")
for i in range(len(a)):
  for j in range(len(a[i])):
    if(i%2==0 and j%2!=0):
      print(a[i][j])

#g) Tính trung bình cộng của các phần tử chẵn thuộc dòng lẻ của a
tong = 0
soluong = 0
for i in range(len(a)):
  if(i%2!=0):
    for j in range(len(a[i])):
      if(a[i][j]%2==0):
        tong += a[i][j]
        soluong += 1
tbc = tong/soluong
print(f"Trung bình cộng của các phần tử chẵn thuộc dòng lẻ của a là: {tbc}")

#h) Tính trung bình cộng các phần tử thuộc biên
tong = 0
soluong = 0
for i in range(len(a)):
  for j in range(len(a[i])):
    if(i==0 or j==0 or i==len(a)-1 or j==len(a[i])-1):
      tong += a[i][j]
      soluong +=1
tbc = tong/soluong
print(f"Trung bình cộng các phần tử thuộc biên là: {tbc}")

# Tính trung bình cộng các phần tử không thuộc biên
tong = 0
soluong = 0
for i in range(len(a)):
  for j in range(len(a[i])):
    if(i!=0 and j!=0 and i!=len(a)-1 and j!=len(a[i])-1):
      tong += a[i][j]
      soluong +=1
tbc = tong/soluong
print(f"Trung bình cộng các phần tử không thuộc biên là: {tbc}")


Nhập dòng: 4
Nhập cột: 4
[[63 32 13 98]
 [80 82 80  2]
 [26 69 39 65]
 [34 34 45 22]]
Dòng muốn xuất: 1
[80 82 80  2]
Cột muốn xuất: 1
32
82
69
34
Dòng lớn nhất là: 0
Cột có tích nhỏ nhất là: 3
Các phần tử thuộc dòng chẵn và cột lẻ trong a là: 
32
98
69
65
Trung bình cộng của các phần tử chẵn thuộc dòng lẻ của a là: 47.714285714285715
Trung bình cộng các phần tử thuộc biên là: 42.833333333333336
Trung bình cộng các phần tử không thuộc biên là: 67.5


In [86]:
from copy import Error
#15) Một sinh viên gồm các thông tin sau:
#Mã sinh viên là chuỗi có 10 ký tự
#Tên là chuỗi tối đa 20 ký tự
#Năm sinh là một số nguyên
#Điểm trung bình là một số thực a
#a) Xây dựng cấu trúc SINHVIEN mô tả một sinh viên
class SINHVIEN:
  def __init__(self, maSV, ten, namSinh, diemTB):
    self.maSV = maSV
    if(maSV.isnumeric() and len(maSV)>=10):
      print("Mã sinh viên phải có 10 ký tự")
      return Error
    if(len(ten)>20):
      print("Tên tối đa 20 ký tự")
      return Error
    self.ten = ten
    self.namSinh = int(namSinh)
    self.diemTB = float(diemTB)

  def OutputSV(self):
    print(f"Mã số SV: {self.maSV} - Tên SV: {self.ten} - SV sinh năm: {self.namSinh} - Điểm: {self.diemTB}")
#b) Cho một mảng có n sinh viên
class DSSV:
  def __init__(self):
    self.dssv = []

  def InputSV(self, n):
    for i in range(n):
      print(f"Nhập thông tin sinh viên thứ {i+1}: ")
      maSV = input("Nhập mã sinh viên: ")
      ten = input("Nhập tên: ")
      namSinh = int(input("Nhập năm sinh: "))
      diemTB = float(input("Nhập điểm trung bình: "))
      print("-------------------------------------")
      sv = SINHVIEN(maSV, ten, namSinh, diemTB)
      self.dssv.append(sv)

  def AddSV(self, sv):
    self.dssv.append(sv)

  def OutputDSSV(self):
    print("--- Danh sách sinh viên ---")
    for sv in self.dssv:
      sv.OutputSV()

#c) Viết hàm cho biết có bao nhiêu sinh viên đủ điều kiện lên lớp
#Biết rằng sinh viên đủ điều kiện lên lớp khi điểm trung bình lớn hơn hoặc bằng 5
  def CheckSVPass(self):
    count = 0
    for sv in self.dssv:
      if sv.diemTB >= 5:
        count += 1
    print(f"Số lượng sinh viên đủ điều kiện lên lớp là: {count}")

#d) Xuất các sinh viên đủ 20 tuổi:
  def CheckSV20(self):
    print("--- Danh sách sinh viên đủ 20 tuổi (==20)---")
    for sv in self.dssv:
      if sv.diemTB == 20:
        sv.OutputSV

#e) Đếm số sinh viên học hệ đại học
  def CheckSVDH(self):
    count = 0
    for sv in self.dssv:
      if sv.maSV[2:4] == "DH":
        count += 1
    print(f"Số lượng sinh viên học hệ đại học là: {count}")

#f) Cho biết trong mảng có bao nhiêu sinh viên có tên <Lan>
  def CheckSVLan(self):
    count = 0
    for sv in self.dssv:
      if sv.ten.endswith("Lan"):
        count+=1
    print(f"Số lượng sinh viên có tên <Lan> là: {count}")

#g) Cho biết trong mảng có bao nhiêu sinh viên có họ <Phan>
  def CheckSVPhan(self):
    count = 0
    for sv in self.dssv:
      if sv.ten[0:5] == "Phan":
        count+=1
    print(f"Số lượng sinh viên có họ <Phan> là: {count}")
#Biết rằng sinh viên hệ DH có mã sinh viên chứa 2 ký tự DH ở vị trí 2, 3 trong chuỗi
#VD: 02DH0001

ds = DSSV()
n = int(input("Nhập số lượng sinh viên: ")) #n sinh viên
ds.InputSV(n)
ds.OutputDSSV()
ds.CheckSVPass()
ds.CheckSVDH()
ds.CheckSVLan()
ds.CheckSVPhan()

Nhập số lượng sinh viên: 2
Nhập thông tin sinh viên thứ 1: 
Nhập mã sinh viên: 01DH
Nhập tên: Phanh Thị Lan
Nhập năm sinh: 2000
Nhập điểm trung bình: 9
-------------------------------------
Nhập thông tin sinh viên thứ 2: 
Nhập mã sinh viên: 02
Nhập tên: Phan Thị Lanh
Nhập năm sinh: 2000
Nhập điểm trung bình: 2
-------------------------------------
--- Danh sách sinh viên ---
Mã số SV: 01DH - Tên SV: Phanh Thị Lan - SV sinh năm: 2000 - Điểm: 9.0
Mã số SV: 02 - Tên SV: Phan Thị Lanh - SV sinh năm: 2000 - Điểm: 2.0
Số lượng sinh viên đủ điều kiện lên lớp là: 1
Số lượng sinh viên học hệ đại học là: 1
Số lượng sinh viên có tên <Lan> là: 1
Số lượng sinh viên có họ <Phan> là: 2
